
package org.irdresearch.tbreach2.shared.model;

// Generated Aug 28, 2011 3:58:51 PM by Hibernate Tools 3.4.0.Beta1

import java.util.Date;

/**
 * Sputumresults generated by hbm2java
 */
public class MonitoringResults implements java.io.Serializable
{

	/**
	 * 
	 */
	private Integer				smearOrderNo;
	private String				patientId;
	private String				healthWorkerId;

	private Date				dateofTreatment;
	private String				baselineSmear;
/*	private String				smearResultMonth2;
	private String				smearResultMonth3;
	private String				smearResultMonth5;
	private String				smearResultMonth6;
	private String				smearResultMonth7;
	private String				smearResultMonth4;
	private String				smearResultMonth6Cat2;
*/	private String				smearResult;
	
	private int 				currentMonth;
	private String 				patientFeel;
	private String 				experienceSideEffects;
	private String				patientSideEffects;
	private String				otherSideEffects;
	private String				patientConsult;
	private String				healthFacility;
	private String				missMedication;
	private String				durationMissMedication;
	private String				medicineWrappers;
	private String				doseConsumption;
	private Date				startTimeForm;
	private Date				endTimeForm;


	public MonitoringResults ()
	{
	}


	public String getOtherSideEffects() {
		return otherSideEffects;
	}



	public void setOtherSideEffects(String otherSideEffects) {
		this.otherSideEffects = otherSideEffects;
	}
	
	

	public String getPatientConsult() {
		return patientConsult;
	}



	public void setPatientConsult(String patientConsult) {
		this.patientConsult = patientConsult;
	}



	public String getPatientFeel() {
		return patientFeel;
	}



	public void setPatientFeel(String patientFeel) {
		this.patientFeel = patientFeel;
	}



	public String getHealthWorkerId() {
		return healthWorkerId;
	}



	public void setHealthWorkerId(String healthWorkerId) {
		this.healthWorkerId = healthWorkerId;
	}



	public Date getDateofTreatment() {
		return dateofTreatment;
	}



	public void setDateofTreatment(Date dateofTreatment) {
		this.dateofTreatment = dateofTreatment;
	}



	public String getBaselineSmear() {
		return baselineSmear;
	}



	public void setBaselineSmear(String baselineSmear) {
		this.baselineSmear = baselineSmear;
	}





	public String getSmearResult() {
		return smearResult;
	}



	public void setSmearResult(String smearResult) {
		this.smearResult = smearResult;
	}



	public int getCurrentMonth() {
		return currentMonth;
	}



	public void setCurrentMonth(int currentMonth) {
		this.currentMonth = currentMonth;
	}



	public String getExperienceSideEffects() {
		return experienceSideEffects;
	}



	public void setExperienceSideEffects(String experienceSideEffects) {
		this.experienceSideEffects = experienceSideEffects;
	}



	public String getPatientSideEffects() {
		return patientSideEffects;
	}



	public void setPatientSideEffects(String patientSideEffects) {
		this.patientSideEffects = patientSideEffects;
	}



	public String getHealthFacility() {
		return healthFacility;
	}



	public void setHealthFacility(String healthFacility) {
		this.healthFacility = healthFacility;
	}



	public String getMissMedication() {
		return missMedication;
	}



	public void setMissMedication(String missMedication) {
		this.missMedication = missMedication;
	}



	public String getDurationMissMedication() {
		return durationMissMedication;
	}



	public void setDurationMissMedication(String durationMissMedication) {
		this.durationMissMedication = durationMissMedication;
	}



	public String getMedicineWrappers() {
		return medicineWrappers;
	}



	public void setMedicineWrappers(String medicineWrappers) {
		this.medicineWrappers = medicineWrappers;
	}



	public String getDoseConsumption() {
		return doseConsumption;
	}



	public void setDoseConsumption(String doseConsumption) {
		this.doseConsumption = doseConsumption;
	}



	public Date getStartTimeForm() {
		return startTimeForm;
	}



	public void setStartTimeForm(Date startTimeForm) {
		this.startTimeForm = startTimeForm;
	}



	public Date getEndTimeForm() {
		return endTimeForm;
	}



	public void setEndTimeForm(Date endTimeForm) {
		this.endTimeForm = endTimeForm;
	}



	public Integer getSmearOrderNo ()
	{
		return this.smearOrderNo;
	}

	public void setSmearOrderNo (Integer smearOrderNo)
	{
		this.smearOrderNo = smearOrderNo;
	}

	public String getPatientId ()
	{
		return this.patientId;
	}

	public void setPatientId (String patientId)
	{
		this.patientId = patientId;
	}


}
