/* Copyright(C) 2015 Interactive Health Solutions, Pvt. Ltd.

This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as
published by the Free Software Foundation; either version 3 of the License (GPLv3), or any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

See the GNU General Public License for more details. You should have received a copy of the GNU General Public License along with this program; if not, write to the Interactive Health Solutions, info@ihsinformatics.com
You can also access the license on the internet at the address: http://www.gnu.org/licenses/gpl-3.0.html

Interactive Health Solutions, hereby disclaims all copyright interest in this program written by the contributors. */

package org.irdresearch.tbreach2.shared.model;

// default package
// Generated Dec 21, 2010 3:45:59 PM by Hibernate Tools 3.4.0.Beta1

/**
 * EncounterResults generated by hbm2java
 */
public class EncounterResults implements java.io.Serializable
{

	/**
	 * 
	 */
	private static final long	serialVersionUID	= -4579364661550124764L;
	private EncounterResultsId	id;
	private String				value;

	public EncounterResults ()
	{
		// Not implemented
	}

	public EncounterResults (EncounterResultsId id, String value)
	{
		this.id = id;
		this.value = value;
	}

	public EncounterResultsId getId ()
	{
		return this.id;
	}

	public void setId (EncounterResultsId id)
	{
		this.id = id;
	}

	public String getValue ()
	{
		return this.value;
	}

	public void setValue (String value)
	{
		this.value = value;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString ()
	{
		return this.id + ", " + this.value;
	}

}
