/* Copyright(C) 2015 Interactive Health Solutions, Pvt. Ltd.

This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as
published by the Free Software Foundation; either version 3 of the License (GPLv3), or any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

See the GNU General Public License for more details. You should have received a copy of the GNU General Public License along with this program; if not, write to the Interactive Health Solutions, info@ihsinformatics.com
You can also access the license on the internet at the address: http://www.gnu.org/licenses/gpl-3.0.html

Interactive Health Solutions, hereby disclaims all copyright interest in this program written by the contributors. */

package org.irdresearch.tbreach2.shared.model;

// Generated Aug 28, 2011 3:01:59 PM by Hibernate Tools 3.4.0.Beta1

/**
 * Labmapping generated by hbm2java
 */
public class LabMapping implements java.io.Serializable
{

	/**
	 * 
	 */
	private static final long	serialVersionUID	= -4033824560272125643L;
	private LabMappingId		id;
	private String				pidrole;

	public LabMapping ()
	{
	}

	public LabMapping (LabMappingId id, String pidrole)
	{
		this.id = id;
		this.pidrole = pidrole;
	}

	public LabMappingId getId ()
	{
		return this.id;
	}

	public void setId (LabMappingId id)
	{
		this.id = id;
	}

	public String getPidrole ()
	{
		return this.pidrole;
	}

	public void setPidrole (String pidrole)
	{
		this.pidrole = pidrole;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString ()
	{
		return id + ", " + pidrole;
	}

}
