/* Copyright(C) 2015 Interactive Health Solutions, Pvt. Ltd.

This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as
published by the Free Software Foundation; either version 3 of the License (GPLv3), or any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

See the GNU General Public License for more details. You should have received a copy of the GNU General Public License along with this program; if not, write to the Interactive Health Solutions, info@ihsinformatics.com
You can also access the license on the internet at the address: http://www.gnu.org/licenses/gpl-3.0.html

Interactive Health Solutions, hereby disclaims all copyright interest in this program written by the contributors. */

package org.irdresearch.tbreach2.shared.model;

// Generated Aug 28, 2011 3:01:59 PM by Hibernate Tools 3.4.0.Beta1

import java.util.Date;

/**
 * Treatmentrefusal generated by hbm2java
 */
public class TreatmentRefusal implements java.io.Serializable
{

	/**
	 * 
	 */
	private static final long	serialVersionUID	= -4046829996787578862L;
	private String				patientId;
	private String				elementRefused;
	private Integer				monthOfSputum;
	private String				reason;
	private Date				caseClosedOnDate;

	public TreatmentRefusal ()
	{
	}

	public TreatmentRefusal (String patientId)
	{
		this.patientId = patientId;
	}

	public TreatmentRefusal (String patientId, String elementRefused, Integer monthOfSputum, String reason, Date caseClosedOnDate)
	{
		this.patientId = patientId;
		this.elementRefused = elementRefused;
		this.monthOfSputum = monthOfSputum;
		this.reason = reason;
		this.caseClosedOnDate = caseClosedOnDate;
	}

	public String getPatientId ()
	{
		return this.patientId;
	}

	public void setPatientId (String patientId)
	{
		this.patientId = patientId;
	}

	public String getElementRefused ()
	{
		return this.elementRefused;
	}

	public void setElementRefused (String elementRefused)
	{
		this.elementRefused = elementRefused;
	}

	public Integer getMonthOfSputum ()
	{
		return this.monthOfSputum;
	}

	public void setMonthOfSputum (Integer monthOfSputum)
	{
		this.monthOfSputum = monthOfSputum;
	}

	public String getReason ()
	{
		return this.reason;
	}

	public void setReason (String reason)
	{
		this.reason = reason;
	}

	public Date getCaseClosedOnDate ()
	{
		return this.caseClosedOnDate;
	}

	public void setCaseClosedOnDate (Date caseClosedOnDate)
	{
		this.caseClosedOnDate = caseClosedOnDate;
	}

}
