/* Copyright(C) 2015 Interactive Health Solutions, Pvt. Ltd.

This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as
published by the Free Software Foundation; either version 3 of the License (GPLv3), or any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

See the GNU General Public License for more details. You should have received a copy of the GNU General Public License along with this program; if not, write to the Interactive Health Solutions, info@ihsinformatics.com
You can also access the license on the internet at the address: http://www.gnu.org/licenses/gpl-3.0.html

Interactive Health Solutions, hereby disclaims all copyright interest in this program written by the contributors. */

package org.irdresearch.tbreach2.shared.model;

// Generated Aug 28, 2011 3:01:59 PM by Hibernate Tools 3.4.0.Beta1

/**
 * Worker generated by hbm2java
 */
public class Worker implements java.io.Serializable
{

	/**
	 * 
	 */
	private static final long	serialVersionUID	= 6504827084321406008L;
	private String				workerId;
	private String				workerRole;

	public Worker ()
	{
	}

	public Worker (String workerId, String workerRole)
	{
		this.workerId = workerId;
		this.workerRole = workerRole;
	}

	public String getWorkerId ()
	{
		return this.workerId;
	}

	public void setWorkerId (String workerId)
	{
		this.workerId = workerId;
	}

	public String getWorkerRole ()
	{
		return this.workerRole;
	}

	public void setWorkerRole (String workerRole)
	{
		this.workerRole = workerRole;
	}

}
