/* Copyright(C) 2015 Interactive Health Solutions, Pvt. Ltd.

This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as
published by the Free Software Foundation; either version 3 of the License (GPLv3), or any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

See the GNU General Public License for more details. You should have received a copy of the GNU General Public License along with this program; if not, write to the Interactive Health Solutions, info@ihsinformatics.com
You can also access the license on the internet at the address: http://www.gnu.org/licenses/gpl-3.0.html

Interactive Health Solutions, hereby disclaims all copyright interest in this program written by the contributors. */

package org.irdresearch.tbreach2.shared.model;

// Generated Aug 28, 2011 3:01:59 PM by Hibernate Tools 3.4.0.Beta1

import java.util.Date;

/**
 * XrayResults generated by hbm2java
 */
public class XrayResults implements java.io.Serializable
{

	/**
	 * 
	 */
	private static final long	serialVersionUID	= 4718984808915692765L;
	private String				patientId;
	private String				xrayOrderedBy;
	private String				xrayLabId;
	private Date				xrayDate;
	private Date				dateReported;
	private String				xrayResult;
	private String				testedBy;
	private String				remarks;

	public XrayResults ()
	{
	}

	public XrayResults (String patientId)
	{
		this.patientId = patientId;
	}

	public XrayResults (String patientId, String xrayOrderedBy, String xrayLabId, Date xrayDate, Date dateReported, String xrayResult, String testedBy, String remarks)
	{
		this.patientId = patientId;
		this.xrayOrderedBy = xrayOrderedBy;
		this.xrayLabId = xrayLabId;
		this.xrayDate = xrayDate;
		this.dateReported = dateReported;
		this.xrayResult = xrayResult;
		this.testedBy = testedBy;
		this.remarks = remarks;
	}

	public String getPatientId ()
	{
		return this.patientId;
	}

	public void setPatientId (String patientId)
	{
		this.patientId = patientId;
	}

	public String getXrayOrderedBy ()
	{
		return this.xrayOrderedBy;
	}

	public void setXrayOrderedBy (String xrayOrderedBy)
	{
		this.xrayOrderedBy = xrayOrderedBy;
	}

	public String getXrayLabId ()
	{
		return this.xrayLabId;
	}

	public void setXrayLabId (String xrayLabId)
	{
		this.xrayLabId = xrayLabId;
	}

	public Date getXrayDate ()
	{
		return this.xrayDate;
	}

	public void setXrayDate (Date xrayDate)
	{
		this.xrayDate = xrayDate;
	}

	public Date getDateReported ()
	{
		return this.dateReported;
	}

	public void setDateReported (Date dateReported)
	{
		this.dateReported = dateReported;
	}

	public String getXrayResult ()
	{
		return this.xrayResult;
	}

	public void setXrayResult (String xrayResult)
	{
		this.xrayResult = xrayResult;
	}

	public String getTestedBy ()
	{
		return this.testedBy;
	}

	public void setTestedBy (String testedBy)
	{
		this.testedBy = testedBy;
	}

	public String getRemarks ()
	{
		return this.remarks;
	}

	public void setRemarks (String remarks)
	{
		this.remarks = remarks;
	}

}
